{% set name = "pentapy" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 46e1d9b13bb78d51f754f30bfc819ed784346205f10d2a5b44b52b711a7b6e26

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools >=64
    - setuptools_scm >=7
    - cython >=3.0.10, <3.1
    - numpy >=1.20.0
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pentapy
  requires:
    - pytest
  source_files:
    - tests
  commands:
    - pytest -vv tests

about:
  home: https://github.com/GeoStat-Framework/pentapy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'pentapy: A toolbox for pentadiagonal matrizes.'
  doc_url: https://pentapy.readthedocs.io/
  dev_url: https://github.com/GeoStat-Framework/pentapy

extra:
  recipe-maintainers:
    - MuellerSeb
