{% set name = "pentapy" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 637ab759966ce3454063d3ff6f065ace8e5ade2ae1acf06861e1666e57bca8f0

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools >=45
    - setuptools_scm >=3.4
    - cython >=0.28.3
    - numpy >=1.14.5
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pentapy
  requires:
    - pytest
  source_files:
    - tests
  commands:
    - pytest -vv tests

about:
  home: https://github.com/GeoStat-Framework/pentapy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'pentapy: A toolbox for pentadiagonal matrizes.'
  doc_url: https://pentapy.readthedocs.io/
  dev_url: https://github.com/GeoStat-Framework/pentapy

extra:
  recipe-maintainers:
    - MuellerSeb
